name : Linting
on : [push]
jobs:
    eslint:
        name : Lint code base
        runs-on : ubuntu-latest

        steps:
            - name: Checkout code 
              uses : actions/checkout@v2

            - name : Move to the netflix-ui directory
              run : cd netflix-ui/
            
            - name: Install packages
              run: npm i

            - name : Run ESlint
              run : npm init @eslint/config

            - name: Run ESlint part 2
              run : npm run lint
              
